import type { Scenario } from "../scenario";
import { happyPath } from "./happy-path";
import { insuranceLapsed } from "./insurance-lapsed";
import { spoofedCarrier } from "./spoofed-carrier";
import { doubleBrokering } from "./double-brokering";
import { brokerOverCeiling } from "./broker-over-ceiling";
import { exposureMidNegotiation } from "./exposure-mid-negotiation";
import { nonConvergence } from "./non-convergence";
import { revokedPrePickup } from "./revoked-pre-pickup";
import { replayAndTamper } from "./replay-and-tamper";
import { multiTender } from "./multi-tender";
import { negotiationTimeout } from "./negotiation-timeout";
import { promptInjection } from "./prompt-injection";
import { venueCrashRecovery } from "./venue-crash-recovery";
import { venueCrashNotification } from "./venue-crash-notification";
import { keyRotation } from "./key-rotation";
import { venueKeyRotation } from "./venue-key-rotation";
import { rootKeyRotation } from "./root-key-rotation";
import { statusTimestamping } from "./status-timestamping";
import { witnessEquivocation } from "./witness-equivocation";
import { witnessCollusion } from "./witness-collusion";
import { delayedRecording } from "./delayed-recording";
import { registryNotRead } from "./registry-not-read";
import { registryQuorum } from "./registry-quorum";
import { registryCollusion } from "./registry-collusion";
import { insuranceRenewal } from "./insurance-renewal";
import { insurerOfRecord } from "./insurer-of-record";
import { insurerKeyBinding } from "./insurer-key-binding";
import { filerOnboarding } from "./filer-onboarding";
import { regulatorKey } from "./regulator-key";

export const SCENARIOS: Scenario[] = [happyPath, insuranceLapsed, spoofedCarrier, doubleBrokering, brokerOverCeiling, exposureMidNegotiation, nonConvergence, revokedPrePickup, replayAndTamper, multiTender, negotiationTimeout, promptInjection, venueCrashRecovery, venueCrashNotification, keyRotation, venueKeyRotation, rootKeyRotation, statusTimestamping, witnessEquivocation, witnessCollusion, delayedRecording, registryNotRead, registryQuorum, registryCollusion, insuranceRenewal, insurerOfRecord, insurerKeyBinding, filerOnboarding, regulatorKey];
export const ADVERSARIAL = SCENARIOS.filter((s) => s.id !== "happy-path");
